### ISSUE TITLE
Bounding boxes popping in and out during a trajectory sequence

### ISSUE THREAD

**Issue by hungdche** [waymo-research/waymax#45]
Thank you for sharing the code! I ran the `data_demo` notebook on a specific tfrecord and notice some bounding boxes seem to disappear/reappear as below. I could interpolate between boxes, but I thought raising the issue here would be less hacky. Thanks!

https://github.com/waymo-research/waymax/assets/90811347/5b8b2aa3-f7b2-488d-9fe3-0a0a556dd57c

**Comment by justinjfu** [comment]
Hi Henry,

This is unfortunately due to perception noise in the Waymo Open Motion Dataset -- you'll notice it normally happens for occluded objects and far-away objects. What's happening is in the underlying data the valid bit for these agents is being flipped off and back on.

There isn't a great way for use to fix it. We decided to leave it as-is because it's similar to the raw perception inputs you would get in a real system. I'll leave this ticket open for now since we've discussed smoothing the flickering internally before but put it on lower priority.
