### ISSUE TITLE
Question Regarding traffic_light Binding to Specific Lane Line

### ISSUE THREAD

**Issue by igo312** [waymo-research/waymax#62]
Hi,

Thank you for open-sourcing this project! I have been using it recently and came across an observation. It seems that the `traffic_light` is bound to a specific point on the lane line by `lane_id`. Could you clarify why this binding is set up this way? I would expect that a traffic_light might be associated with multiple lane lines. How does the system handle such scenarios?

Looking forward to your response!

**Comment by nicomon24** [comment]
Hi @igo312,

The state inside traffic light is attached to a specific lane because we preferred to have a "flat" hierarchy between the 2, so traffic lights are "repeated" if they belong to multiple lanes.
Actually, if you look at the underlying data proto [TrafficSignalLaneState](https://github.com/waymo-research/waymo-open-dataset/blob/5f8a1cd42491210e7de629b6f8fc09b65e0cbe99/src/waymo_open_dataset/protos/map.proto#L39), you can notice that this is a "LaneState".
